spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**

            - id: auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: booking-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/bookings/**

            - id: room-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/rooms/**

jwt:
  secret: YourSuperSecretKeyAtLeast32CharsLong123!
  expirationMinutes: 60
