spring:
  application:
    name: booking-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/booking_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

    hikari:
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8082}

jwt:
  secret: ${JWT_SECRET:YourSuperSecretKeyAtLeast32CharsLong123!}
  expirationMinutes: ${JWT_EXPIRATION_MINUTES:60}

services:
  user:
    url: ${USER_SERVICE_URL:http://localhost:8081}

  audit:
    url: ${AUDIT_SERVICE_URL:http://localhost:8083}